### ISSUE TITLE
Un-pressing the party button 

### ISSUE THREAD

**Issue by WillNilges** [ComputerScienceHouse/RTP-Todo#13]
When are we turning power back on?

RIT cut power to dorms at 9AM today. I can clear my schedule whenever to start turning stuff on. Do we wanna hold off for a bit to do stuff (@galenguyer you mentioned cable management)?

Y'know what? Here's a checklist:
- [x] Cable Management
- [ ] Kick people off the UPS
- [x] Wait for RIT to give the all-clear
- [x] Wait for both AC units to be running
- [x] Additional waiting period (y'know, just in case)
- [x] ???
- [x] Un press the party button
- [x] Turn stuff back on

**Comment by galenguyer** [comment]
How serious are we about cable management? If we really want to do that now, I'd say we should get cable ties and start that tonight. I'm on the fence about it though because we're about to get new hardware and will have to re-manage everything

**Comment by galenguyer** [comment]
Also, for the checklist: We need the other AC unit to come back before we can turn stuff on

**Comment by galenguyer** [comment]
Today's update: If we're lucky we'll get power back in the evening. We did a bit of cable management but not much, I'm fine with that though as we can do it properly when we get new hardware. Both AC units were running fine when the generator was on so I'm not worried about that anymore. The one thing I want to make sure we do before we start stuff back up again is audit the UPS PDUs and make sure only Ceph and Proxmox are attached.

**Comment by galenguyer** [comment]
@mxmeinhold brings up a good point: We need to let the UPS charge before we restore power to the servers.

**Comment by mxmeinhold** [comment]
I would leave at least freedom on the ups. Its been useful in the past. My concern is more the user rack.

**Comment by WillNilges** [comment]
@galenguyer @Mstrodl @klauscurde do we still need to audit the PDUs? Close this issue if not.

**Comment by galenguyer** [comment]
Yeah, we didn't do that. I can do that today.

**Comment by galenguyer** [comment]
UPS audited. Closing this as we're back to full operational capacity.
