### ISSUE TITLE
Drive Wipes and Certification

### ISSUE THREAD

**Issue by klauscurde** [ComputerScienceHouse/RTP-Todo#18]
In order to be compliant with the NDA, we need to wipe every single drive that we receive. The details of the standard we are allowed to use are still being fleshed out, we only know it needs to be DoD 7 and have some example certificates. I'm waiting to hear back from Fred on whether we could use SANITIZE, @Mstrodl knows more about this.

We will have to be responsible for wiping the drives by either doing it ourselves with software that generates a certificate, or going through a company in Rochester that could come in and do the wipes for us. We could ask for a discount because we're a university organization but it may still cost a bit to go that route. 

Discussion on the process we use, software, logistics, etc. heavily encouraged here.

**Comment by galenguyer** [comment]
We should reach out to the Rochester company and get a rough quote and see how feasible that is. That seems the easier route, but also if we can wipe them here (like, we don't have to do it in Boston), that makes the logistics a ton easier.

**Comment by klauscurde** [comment]
Wiping them in Boston is difficult enough to not be an option imo. We'd have to coordinate getting there, taking the machines to them or somehow getting them to visit Wayfair, and then being there long enough for the company to get the job done. It's very logistically difficult. It's much easier for us to just grab them quickly and take care of it all here.

**Comment by Mstrodl** [comment]
As an update: I believe Wayfair said they'd do this for us... CC @klauscurde

**Comment by klauscurde** [comment]
Fred said that he's not 100% sure that Wayfair is going to do it, so I'd wait to close this until we know for certain.

**Comment by klauscurde** [comment]
Johonnot is wiping all of the drives for us, and we will be paying for shipping from them.
