### ISSUE TITLE
Take over the Luser Center

### ISSUE THREAD

**Issue by WillNilges** [ComputerScienceHouse/RTP-Todo#2]
Are we doing Fred Center? If we're doing Fred Center, we need to figure out these things:
- [ ] What are we calling it?
- [ ]  Rack Placement
- [ ]  Power delivery
- [ ]  Data delivery
- [ ]  Access control
- [ ]  What in god's name to do with all the furniture in there right now

**Comment by klauscurde** [comment]
Update: I estimated that the Luser Center could hold 5 of the largest-model racks Wayfair is providing, so for now that's the tentative plan for what it will hold. It will likely hold excess stuff for a while as we make the transition from old stuff to new.

**Comment by galenguyer** [comment]
Copying this from my comment in #5: 

Going to have a hot take here: We shouldn't take over other social rooms permanently. I think using the LUser center as staging is fine, but I'm against removing social spaces in favor of having more compute locations. The Software Room and LUser center are used often and we shouldn't take those away. We'll have way more than enough compute power with the new servers in the server room.

**Comment by WillNilges** [comment]
You know, through all of this, I've been thinking about that. I'm leaning towards the opinion that the cost/benefit of taking over the Luser center isn't good enough, and we probably shouldn't do it.

I'm gonna close this. Someone else can open it if they have a compelling enough reason.
